# Generated by Django 6.0 on 2026-02-25 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=200)),
                ('star_rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star'), (6, '6 Star'), (7, '7 Star')])),
                ('year_built', models.IntegerField()),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('use_current_location', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('house_no', models.CharField(blank=True, max_length=150)),
                ('area', models.CharField(blank=True, max_length=150)),
                ('pincode', models.CharField(blank=True, max_length=6)),
                ('country', models.CharField(default='India', max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('amenities', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('room_type', models.CharField(choices=[('deluxe', 'Deluxe'), ('standard', 'Standard'), ('luxury', 'Luxury'), ('master', 'Master'), ('common', 'Common'), ('family', 'Family Room'), ('honeymoon', 'For Honeymooners'), ('other', 'Other')], max_length=20)),
                ('bed_type', models.CharField(choices=[('single', 'Single Bed'), ('double', 'Double Bed'), ('twin', 'Twin Bed'), ('soft', 'Soft Bed'), ('standard', 'Standard Bed'), ('king', 'King Bed'), ('queen', 'Queen Bed'), ('1k_2t', '1 King or 2 Twin Bed'), ('1q_2t', '1 Queen or 2 Twin Bed')], max_length=20)),
                ('view_type', models.CharField(choices=[('no', 'No View'), ('sea', 'Sea'), ('valley', 'Valley'), ('hill', 'Hill'), ('pool', 'Pool'), ('garden', 'Garden'), ('lake', 'Lake'), ('forest', 'Forest'), ('palace', 'Palace'), ('beach', 'Beach'), ('mountain', 'Mountain'), ('airport', 'Airport'), ('harbor', 'Harbor')], max_length=20)),
                ('smoking_allowed', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=5)),
                ('extra_bed_allowed', models.BooleanField(default=False)),
                ('extra_bed_type', models.CharField(blank=True, choices=[('mattress', 'Mattress'), ('cot', 'Cot'), ('sofa', 'Sofa Cum Bed')], max_length=20, null=True)),
                ('base_adult', models.PositiveIntegerField(default=2)),
                ('min_adult', models.PositiveIntegerField(default=1)),
                ('min_child', models.PositiveIntegerField(default=0)),
                ('max_occupancy', models.PositiveIntegerField()),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra_adult_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('child_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_categories', to='hotels.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('maintenance', 'Maintenance'), ('blocked', 'Blocked')], default='available', max_length=20)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.hotel')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.roomcategory')),
            ],
        ),
        migrations.CreateModel(
            name='RoomAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('booked_rooms', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='hotels.roomcategory')),
            ],
            options={
                'unique_together': {('category', 'date')},
            },
        ),
    ]
