# Generated by Django 6.0 on 2026-02-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotelimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelimage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='hotelimage',
            name='is_cover',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
